[package]
name = "multikey"
version = "0.1.0"
edition = "2021"
authors = ["Dave Huseby <dwh@linuxprogrammer.org>"]
description = "Multikey self-describing cryptographic key data"
repository = "https://github.com/cryptidtech/multikey.git"
readme = "README.md"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0"
hex = "0.4"
multibase = "0.9"
multicodec = { version = "0.2", git = "https://github.com/cryptidtech/rust-multicodec.git" }
rand = "0.8"
ssh-key = { version = "0.6.2", features = ["alloc", "crypto", "ed25519"]}
thiserror = "1.0"
unsigned-varint = "0.7"
