[package]
name = "multikey"
version = "0.4.0"
edition = "2021"
authors = ["Dave Huseby <dwh@linuxprogrammer.org>"]
description = "Multikey self-describing cryptographic key data"
repository = "https://github.com/cryptidtech/multikey.git"
readme = "README.md"
license = "Apache-2.0"

[features]
default = ["serde"]

[dependencies]
bcrypt-pbkdf = "0.10"
ed25519-dalek = { version = "2.0", features = ["rand_core"] }
hex = "0.4"
multibase = "0.9"
multicodec = { version = "0.3", git = "https://github.com/cryptidtech/rust-multicodec.git" }
multihash = { version = "0.2", git = "https://github.com/cryptidtech/multihash.git" }
multitrait = { version = "0.1", git = "https://github.com/cryptidtech/multitrait.git" }
multiutil = { version = "0.2", git = "https://github.com/cryptidtech/multiutil.git" }
rand = "0.8"
sec1 = "0.7"
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"], optional = true }
sodiumoxide = "0.2"
ssh-key = { version = "0.6.2", features = ["alloc", "crypto", "ed25519"]}
thiserror = "1.0"
typenum = "1.17"
unsigned-varint = { version = "0.8", features = ["std"]}
zeroize = "1.6"

[dev-dependencies]
serde_test = "1.0"
serde_json = "1.0"
